version: 1
disable_existing_loggers: false
log_directory: ../log
formatters:
  simple:
    format: "%(asctime)s %(name)s:%(lineno)s %(funcName)s [%(levelname)s]: %(message)s"
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: "ext://sys.stdout"
  fileHandler:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: ../log/app.log
root:
  level: INFO
  handlers:
    - consoleHandler
    - fileHandler